### ISSUE TITLE
No settings.php

### ISSUE THREAD

**Issue by username1290** [jasonmajors/app-tracking-project-php#1]
Hi, there's no settings.php

i.e. opening header.inc.php says:

<?php include 'settings.php'; ?>

**Comment by jasonmajors** [comment]
Hello, just saw this. The settings.php file is in the .gitignore because it contains the constants USERNAME and PASSWORD for the database. The file is pretty simple though, it's just those 2 constants and the $PATH variable (string) for the links, in this case '/app-tracking-project/'.

Thanks!
